### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList

### ISSUE THREAD

**Issue by Malgosiatobiasz1** [galexandre/sonar-cobertura#41]
Hi , there  is an issue during project analysis in SonarQube, also I have a question, is this plugin still maintained ?

Plugin version : Cobertura 2.0 (cobertura)
Sonarqube version 10.2.1
SonarScanner 5.0.1.3006

ERROR: Error during SonarScanner execution
java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
	at org.sonar.plugins.cobertura.CoberturaPlugin.getExtensions(CoberturaPlugin.java:35)
	at org.sonar.plugins.cobertura.CoberturaPlugin.define(CoberturaPlugin.java:50)
	at org.sonar.scanner.bootstrap.ExtensionInstaller.install(ExtensionInstaller.java:57)
	at org.sonar.scanner.scan.SpringProjectScanContainer.addScannerExtensions(SpringProjectScanContainer.java:323)
	at org.sonar.scanner.scan.SpringProjectScanContainer.doBeforeStart(SpringProjectScanContainer.java:154)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:186)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:139)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:71)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:65)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at jdk.proxy1/jdk.proxy1.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:126)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
	at org.sonarsource.scanner.cli.Main.main(Main.java:62)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)

**Comment by Malgosiatobiasz1** [comment]
Similar to https://community.sonarsource.com/t/sonar-execution-is-failing-in-sonar-scanner-cli-latest-image/115919 
use previous version on sonar-scanner-cli image to fix this issue.
